### ISSUE TITLE
In typescript has this error

### ISSUE THREAD

**Issue by wustzhaohui** [vasturiano/circlepack-chart#5]
Type '{ name: string; value: number; }' is not assignable to type 'Node'.
  Object literal may only specify known properties, and 'value' does not exist in type 'Node'.  TS2322

    11 |           {
    12 |             name: "leafA",
  > 13 |             value: 3
       |             ^
    14 |           },
    15 |           {
    16 |             name: "nodeB",

**Comment by vasturiano** [comment]
@wustzhaohui have you tried correctly typing your node objects by extending the baseline `Node`?
```js
import { Node } from 'circlepack-chart'; 
...
interface MyNode extends Node {
  value: number;
}
```

**Comment by wustzhaohui** [comment]
there has another problem. It can not draw when the data is too large.

by the way do you have any contact？

this is my Telegram +8618601780983 fred zhao

**Comment by vasturiano** [comment]
@wustzhaohui if you have an issue with the rendering, could you make a quick example on codepen.io, so it can be debugged further?

**Comment by wustzhaohui** [comment]
> @wustzhaohui if you have an issue with the rendering, could you make a quick example on codepen.io, so it can be debugged further?

I solved it by set the value type as number.
