### ISSUE TITLE
[Question] Is There a possibiliy to support canvas render ?

### ISSUE THREAD

**Issue by khofaai** [vasturiano/circlepack-chart#7]
Hi, 
im using this package, it works fine the issue is i have some big object and svg rendering + animation is really slow, and im asking are you considering to add canvas rendering in the future ? Thanks

**Comment by vasturiano** [comment]
@khofaai thanks for reaching out.

It's a good idea, specially to help with rendering performance. But using Canvas would be nearly a complete re-write of this component. Plus, it makes the interaction parts of the module much more complicated as you can't rely on DOM node native events.

I would say that such an effort should probably be in a fork repo of this one, to not over-complicate the code base.

**Comment by khofaai** [comment]
Hi @vasturiano Thanks for the reply,

Yes ofc, I've tried to integrate canvas as an option but i didn't manage x), thanks for explain it to me, now i have a clear idea of what i need,

Thanks
