### ISSUE TITLE
[QUESTION]: How to know if the circle drawing ended ?

### ISSUE THREAD

**Issue by khofaai** [vasturiano/circlepack-chart#9]
Hi, 

I hope you're doing well, i'm looking on a way to know if the drawing has ended and i don't know if i can do that already ?

Thanks 😄

**Comment by vasturiano** [comment]
@khofaai I don't think there is a way to do that currently. Once the DOM changes are passed on to the browser rendering engine, it will manage that process without notifying when the drawing is complete.

**Comment by khofaai** [comment]
@vasturiano Alright, thank you i wasn't sure to be honest that why i've asked you 😆 ,
